version: '3.8'

services:
  sleep-plus-admin:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - FRONTEND_PORT=5173
      - VITE_API_URL=https://sleep-plus-admin-app.sleep-plus-admin.easypanel.host
      - VITE_APP_NAME=Sleep+ Admin
      - VITE_APP_VERSION=1.0.0
      - VITE_ENABLE_DEVTOOLS=false
    volumes:
      - db-data:/app/db.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s

volumes:
  db-data:
